name: Github Pages Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # concurrency:
    #   group: ci-${{ github.ref }}
    #   cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        # with:
        #   persist-credentials: false

      - name: Install and Build
        run: |
          npm i
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4.1.0
        with:
          branch: gh-pages
          target-folder: site
          ssh-key: ${{ secrets.DEPLOY_KEY }}
