name: Github Pages Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # concurrency:
    #   group: ci-${{ github.ref }}
    #   cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   persist-credentials: false

      - name: Build
        run: |
          npm i
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          clean: true
